version: "3"
services:

  ganache:
    image: "trufflesuite/ganache-cli:latest"
    command: -b 1
    ports:
      - "8545:8545"

#  metastore:
#    image: holochain/holochain-rust
#    command: hc package && hc run --logging
#    volumes:
#      - "./packages/metastore/app:/holochain"

  squad-games:
    build: .
    command: npm run start
    working_dir: /app/packages/squad-games-web
    ports:
      - "3000:3000"
    volumes:
      - "./packages/squad-games-web:/app/packages/squad-games-web"
      - "./packages/curation-market/clients/js:/app/packages/curation-market/clients/js"
      - "./packages/metastore/clients/js:/app/packages/metastore/clients/js"
      - "./packages/squad-sdk/js:/app/packages/squad-sdk/js"

  app-spec:
    build: .
    command: npm run start
    working_dir: /app/packages/app-spec-web
    ports:
      - "3001:3000"
    volumes:
      - "./packages/app-spec-web:/app/packages/app-spec-web"
      - "./packages/curation-market/clients/js:/app/packages/curation-market/clients/js"
      - "./packages/metastore/clients/js:/app/packages/metastore/clients/js"
      - "./packages/squad-sdk/js:/app/packages/squad-sdk/js"
