.PHONY: develop
develop:
	# Installing ganache...
	cd curation && npm install && cd api && npm rebuild
	# Starting ganache...
	-ganache-cli -b 1 &> ganache.log &
	# Deploying contracts...
	cd curation && npm run deploy-local
	# Packaging holochain DNA...
	cd metastore && hc package
	# Starting holochain test conductor...
	-cd metastore && hc run --logging

.PHONY: react
react:
	# Installing ui packages...
	cd ui && npm install
	# Linking ui to sdk, adding holochain test entries, and starting React app...
	cd sdk/js && npm install && npm link && cd ../../ui && npm link squad-sdk && cd test && node makeEntries && cd .. && npm run start