version: 2

jobs:
 build:
  docker:
   - image: nixorg/nix:circleci
  environment:
   # this should match revision in nixpkgs/nixpkgs.nix
   NIX_PATH: nixpkgs=https://github.com/NixOs/nixpkgs-channels/tarball/8634c3b619909db7fc747faf8c03592986626e21
  steps:
   - checkout
   # smoke test
   - run: nix-shell -vvv --run echo
