on: [push]

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - run: |
        docker build packages/metastore/mock -t squadgames/mock-metastore:${{ github.sha }}
        docker push squadgames/mock-metastore:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'mock-metastore'
        images: 'squadgames/mock-metastore:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout
